// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBssEJne-_ab0eqFaWwkwiWGRrL02fvJAk',
    appId: '1:414800048929:web:7d6a500218860632dc0460',
    messagingSenderId: '414800048929',
    projectId: 'akashflutter-54cb7',
    authDomain: 'akashflutter-54cb7.firebaseapp.com',
    storageBucket: 'akashflutter-54cb7.appspot.com',
    measurementId: 'G-RGQ9L51WQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDoJuh65DWx5ycNvN_Zp8bMfqzmG8UNQg',
    appId: '1:414800048929:android:44837eab3a3647dcdc0460',
    messagingSenderId: '414800048929',
    projectId: 'akashflutter-54cb7',
    storageBucket: 'akashflutter-54cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_7dKSmL1Q3JZL-b8wlecge1Bikdv1Mwc',
    appId: '1:414800048929:ios:7235a14fbfccccbedc0460',
    messagingSenderId: '414800048929',
    projectId: 'akashflutter-54cb7',
    storageBucket: 'akashflutter-54cb7.appspot.com',
    iosBundleId: 'com.example.akashflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_7dKSmL1Q3JZL-b8wlecge1Bikdv1Mwc',
    appId: '1:414800048929:ios:7235a14fbfccccbedc0460',
    messagingSenderId: '414800048929',
    projectId: 'akashflutter-54cb7',
    storageBucket: 'akashflutter-54cb7.appspot.com',
    iosBundleId: 'com.example.akashflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBssEJne-_ab0eqFaWwkwiWGRrL02fvJAk',
    appId: '1:414800048929:web:7190586e3a7b6e06dc0460',
    messagingSenderId: '414800048929',
    projectId: 'akashflutter-54cb7',
    authDomain: 'akashflutter-54cb7.firebaseapp.com',
    storageBucket: 'akashflutter-54cb7.appspot.com',
    measurementId: 'G-TSB5TP1BFY',
  );
}
